### PR TITLE
Allow kill to work for rsync when run via %

### PR DESCRIPTION
**Pull request by laktak**
I'm using rsync for my paste command:

```
cmd paste-rsync %{{
    set -- $(cat ~/.local/share/lf/files)
    mode="$1"; shift
    case "$mode" in
        copy) rsync -rltphv "$@" . ;;
        move) mv -- "$@" .; lf -remote "send clear" ;;
    esac
}}
```

However when running it via `%` I'm not able to kill the process (`cmd-interrupt` will send the kill signal to the shell process but not to its children). This is not an issue for `$` and `!`.

This PR places the process in its own process group on linux and macOS (where I am able to test) and `cmd-interrupt` is then able to send the exit signal to the whole group.

### CODE REVIEW

**Comment by gokcehan** [comment]
@laktak A patch for such a change should likely address #694 and #734 somehow. Also what's the situation with other unix systems? I don't really want to maintain platform specific patches.

**Comment by laktak** [comment]
Yes #694 is also discussing the process group of shell-async in addition to shell-pipe that is handled here. @slavistan do you have any input/would you be willing to test once shell-async is handled by this PR as well?

As for #734 - this is a separate issue IMO. Also there appears to be a simple workaround.

I understand that you don't want to implement platform specific patches. I think that this PR should work on all POSIX systems as it is documented for these systems. This patch would still not support Solaris, Illumos, and Windows - is that OK in this context?

**Comment by gokcehan** [comment]
@laktak Having separate windows is ok, that's why we have `os.go` and `os_windows.go` files. I'm not sure if we have any actual users with Solaris and Illumos but Github shows some downloads so we should not break the builds if possible for whatever it's worth. "syscall" in your patch seems to break the build on these systems. I think it is time we should switch to [golang.org/x/sys](https://pkg.go.dev/golang.org/x/sys) package. The old "syscall" package is frozen and deprecated anyway.

**Comment by laktak** [comment]
Thanks for pointing out the x/sys package! I was able to move the code into os/os_windows. The PR now also includes shell-async.

**Comment by gokcehan** [comment]
@laktak Looks good, thanks for the patch.

**Comment by slavistan** [comment]
@laktak Can confirm that this PR fixes #694. Thank you!

**Pull request merged**
