### PR TITLE
Add history-back and history-forward commands

### PR DESCRIPTION
**Pull request by laktak**
This PR implements a history that works similar to a browser. It allows you to travel back and forward on the directories you visited. Each client has its own history.

It also implements two default keybindings `[` and `]` but I can remove them if you prefer to keep this optional.

This is also, if I understood correctly, what was requested in #212, where it was called a jump list.

And sorry if I am overwhelming you with PRs. It's just that I really like lf after having been on ranger for too long ;)

### CODE REVIEW

**Comment by gokcehan** [comment]
@laktak Just a quick note, PR's are perfectly fine and certainly appreciated. Sorry, I have been quite busy this week and I couldn't get back to you. My free time is often sporadic. I will eventually get back to you, hopefully in the weekend. In the meantime, maybe other people can test the patches and drop some feedback.

**Comment by laktak** [comment]
@gokcehan No problem, take your time. I understand perfectly.

**Comment by gokcehan** [comment]
@laktak Well, we use "history" to refer to the command line history so I think it is better to call these "jumps". Also we use "next" and "prev" for the rest of the commands so ideally these commands should be named "jump-next" and "jump-prev" accordingly.

**Comment by laktak** [comment]
OK

**Comment by gokcehan** [comment]
@laktak Looks good, thanks for the patch.

**Pull request merged**
