### PR TITLE
538-dirsize-from-script

### PR DESCRIPTION
**Pull request by abarri**
This contribution addresses #538. It provides a new option, `dirsize_tool`, which is a string pointing to an external script that accepts one argument, a path to a directory, and prints the size of this directory (or -1 if it could not be computed). The value of `dirsize_tool` is the empty string by default, so the feature needs to be manually enabled. The directory sizes are computed asynchronously and directly shown in the file manager.

The script below demonstrates the possibilities of this feature. Save it as e.g. "/usr/bin/get_dir_size" and add the following line to lfrc: `set dirsizetool "/usr/bin/get_dir_size"`.
```
#!/usr/bin/env bash
path_dir=$(realpath "$1")

out=$(timeout 1s du -sb "$path_dir" 2> /dev/null | cut -f1)

# Remove the for loop below if duc is not installed.
for i in {1..100}; do
    if [ -n "$out" ]; then
        echo "$out"
        exit 0
    fi
    sleep 0.1s
    out=$(/usr/bin/duc ls --bytes --directory --quiet "$path_dir" 2> /dev/null | cut -d ' ' -f1)
done
# ---

echo $out
exit 0
``` 
Note that this script relies on the [duc](https://duc.zevv.nl/) tool. If this tool is not available on your system then you can remove the for loop as indicated in the comments. 

I achieved the best results when retrying the duc tool for a period of 10s to overcome IO limitations. But this configuration should be adapted to the user needs and the system specifications.

It is sometimes useful to manually retry the dirsize computations that failed to finish in time. To this end, you can use the new command `update-dirsize` (only directory sizes that could not be fetched are recomputed). 

Thanks in advance for your review!

### CODE REVIEW

**Comment by gokcehan** [comment]
@abarri I don't think it is wise to spawn a shell process for each directory. This can act as a shell bomb for crowded directories.

I'm thinking of creating a wiki page to list patches that are not merged into the base so users interested in these features can find them easier. Maybe you can list this patch there if you intend to maintain it in the future.

**Comment by abarri** [comment]
That is a valid remark. The code above spawns one shell process per visible directory even if it is not visited by the user. One way to reduce shell processes is to let the script return a list of sizes of all subdirectories so that there is only one process per directory visit. It could be interesting to add tests for measuring the load and performance on a much larger number of directories. Let me know if I can be of any help in the future.

**Comment by vaclavbenes** [comment]
@abarri  What about to add https://stackoverflow.com/questions/32482673/how-to-get-directory-total-size calc size into lf. I am also looking on this feature. Maybe cache this and read file with metadata ?

**Comment by gokcehan** [comment]
@vaclavbenes I think we already have that logic implemented for copying in `copySize` function in `copy.go` file. It might be possible to use that for this purpose as well.

**Pull request closed without merging**
