### PR TITLE
Add icons support

### PR DESCRIPTION
**Pull request by Deedone**
[Nerd fonts](https://github.com/ryanoasis/nerd-fonts) is needed for this to work
image

### CODE REVIEW

**Comment by gokcehan** [comment]
@Deedone Thanks for working on this. Someone has recently opened a related issue about this as #158. In that issue, I mention I was hoping for a configurable mechanism for icons. Hardcoded defaults could be fine as a start but I'm a little worried about having nerd font as a dependency. There are a lot of users who does not have these special fonts installed and when they activate `icons` option, they will only see blank squares and wonder if there is anything wrong with the option which can be annoying without a configuration mechanism. We could have tried some unicode icons but they are quite limited and the fonts people use might also miss some of these glyphs.

Do you have any plans for a configuration mechanism for this feature? My initial plan was to integrate icons with colors, but it may or may not be a good idea.

Also I was wondering, where did you get the list of default icons for different filetypes?

**Comment by Deedone** [comment]
Yeah I was thinking about configuration mechanism, but not sure how to make it convenient. I think we can reduce the default set of icons to only unicode(or maybe FontAwesome which is more popular) and leave the rest for user configuration. If you have thoughts about how it should look, I will be happy to hear and try to implement them. My best suggestion is something like "addicon %extension% %glyph%" that would add or overwrite icon in list, and can be used multiple times. List of icons is from [here](https://github.com/alexanderjeurissen/ranger_devicons/blob/master/devicons.py)

**Comment by gokcehan** [comment]
@Deedone I'm not very comfortable with copying things from other repositories. In this case, that repository seems to have a GPL license which I think is not compatible with ours. Even if this is simply configuration thing, it can still be a problem and I don't want any headaches about this.

If you ask me, having font awesome as default would not be so different than having nerd fonts. Also I think most symbols we need comes from devicons anyway. So maybe sticking to unicode by default would be more appropriate, although there are not many useful things in unicode. We could add a directory icon for directories, maybe an open directory icon for the current selected directory, and a document icon for the rest.

    🗀 Folder         U+1F5C0
    🗁 Open Folder    U+1F5C1
    🗎 Document       U+1F5CE

This may not be difficult but I'm not sure if this will be enough for users expectations. I think it might be better to prioritize a configuration mechanism first for this feature. I think the easiest way would be to add this as an environment variable such as `LF_ICONS` with a syntax similar to `LS_COLORS`.

**Comment by gokcehan** [comment]
@Deedone I have now pushed a commit to add a configurable icons feature. I have also added a wiki page to describe the configuration. Closing this PR now. Thanks for spending time on this.

**Pull request closed without merging**
