### PR TITLE
Print message in status line after copying/moving

### LINKED ISSUE #276: Copy/Move Sucess to Massage Line
Display a message of success on successful copy/move (in green). Sometimes, I don't know what `lf` was doing being open after a long copy operation; there is just no way to tell. This may be possible to change locally, but I don't like to change core commands if possible.

### PR DESCRIPTION
**Pull request by YerinAlexey**
Closes #276

### CODE REVIEW

**Comment by gokcehan** [comment]
@YerinAlexey I think we should only do this if there are no errors, otherwise any possible error message is immediately overridden.

Also since we do the directory copying recursively, `len(srcs)` may not correspond to the actual number of files copied. Do you think that can be misleading? Maybe just a simple message like `copy success` would be better?

**Comment by YerinAlexey** [comment]
@gokcehan Thanks for the response. I've fixed all that

**Comment by gokcehan** [comment]
@YerinAlexey You're only checking the error for directory loading. You should be checking `errCount == 0`.

Also, this is an async command, so you should be sending the message to the channel instead of directly printing it yourself, otherwise there is a race.

**Comment by YerinAlexey** [comment]
> @YerinAlexey You're only checking the error for directory loading. You should be checking `errCount == 0`.

Thanks, fixed it

> Also, this is an async command, so you should be sending the message to the channel instead of directly printing it yourself, otherwise there is a race.

If I understood correctly, it should look like this:
```go
echosuccess := &callExpr{"echo", []string{""}, 1}
echosuccess.args[0] = "\033[0;32mCopied successfully\033[0m"

ui.exprChan <- echosuccess
```

**Comment by gokcehan** [comment]
@YerinAlexey Thanks for the patch.

**Pull request merged**
