### PR TITLE
[t]csh files added (lfcd,lf-complete)

### PR DESCRIPTION
**Pull request by nereusx**

### CODE REVIEW

**Comment by gokcehan** [comment]
@nereusx Thanks for adding these. We currently name these files with the convention that `lf.sh` is for the completion and `lfcd.sh` is for the change dir command. So can you rename the first file to `lf.csh`?

**Comment by nereusx** [comment]
Its ok now?

**Comment by gokcehan** [comment]
@nereusx Seems ok to me though I don't have tcsh installed to give this a try. What's the deal with keybindings in tcsh? You seem to have left it empty. If keybindings are not supported in tcsh, should we not just remove that part of the comment?

Sorry for taking too long to respond by the way. I have been quite busy and I feel a little overwhelmed by the activity going on in lf.

**Comment by nereusx** [comment]
Github does not shows control-characters; well, I've changed to string, tested in tcsh and posted :)

**Comment by gokcehan** [comment]
@nereusx Ah ok, I didn't realize there is a control character there. Seems good to me now. Thanks for the patch.

**Pull request merged**
