### PR TITLE
Add tags

### PR DESCRIPTION
**Pull request by sant0s12**
This addresses #400. It works similarly to ranger's tags. They default keymap is "t" to add the "*" tag or to remove the existing one but you can also use the :tag command followed by a single character to tag the file with that character.

I hope this is helpful, I really missed this feature when I switched from ranger to lf so I decided to implement it myself.

This is my first time writing anything in go, so any feedback is appreciated :)

### CODE REVIEW

**Comment by gokcehan** [comment]
@sant0s12 Thanks for working on this. In general it looks pretty good. A couple of remarks below.

There are some small issues with the documentation. First, `tag-toggle` in its current behavior is not a modal command so `(modal)` should be removed. Next, `tag` and `tag-toggle` should be added to the "Quick Reference" section as well. Lastly, `tags` file should be mentioned in the "Configuration" section.

I also have a couple of questions and ideas in case you are interested:

- Have you considered tag toggling multiple files at once with the multiple selection? Ranger seems to work as such.
- Have you considered using `rune` instead of `byte` to be unicode friendly? More specifically, I think a tag is meant to be a single width character possibly consisting of multiple runes so the use of string might be required with some checks.
- Is there a reason `tag` is a modal command? This might prevent users from binding different keybindings for different tags. For example, if unicode tags are allowed (i.e. above point) some users may want to have different icons assigned to different keys.
- Should there be an option to configure the default tag? (maybe some of the above points might allow configuring the default tag without an explicit option)
- Regarding `tagcolor` option, some of our existing options uses fmt style configuration (e.g. `errorfmt`, `promptfmt`,

**Comment by gokcehan** [comment]
@sant0s12 Sorry, wrong click I was just writing a review, give me a min.

**Comment by gokcehan** [comment]
@sant0s12 Thanks for working on this. In general it looks pretty good. A couple of remarks below.

There are some small issues with the documentation. First, `tag-toggle` in its current behavior is not a modal command so `(modal)` should be removed. Next, `tag` and `tag-toggle` should be added to the "Quick Reference" section as well. Lastly, `tags` file should be mentioned in the "Configuration" section.

I also have a couple of questions and ideas in case you are interested:

- Have you considered tag toggling multiple files at once with the multiple selection? Ranger seems to work as such.
- Have you considered using `rune` instead of `byte` to be unicode friendly? More specifically, I think a tag is meant to be a single width character possibly consisting of multiple runes so the use of `string` might be required with some checks.
- Is there a reason `tag` is a modal command? This might prevent users from binding different keybindings for different tags. For example, if unicode tags are allowed (i.e. above point) some users may want to have different icons assigned to different keys.
- Should there be an option to configure the default tag? (maybe some of the above points might allow configuring the default tag without an explicit option)
- Regarding `tagcolor` option, some of our existing options uses fmt style configuration (e.g. `errorfmt`, `promptfmt`), so perhaps this should also be `tagfmt` for consistency.
- There has been some talk for adding configuration for selection/copy/paste displays in #754 which would then clash with tags. Is it possible to move the tag display to the next character right next to the filename as in ranger?

**Comment by sant0s12** [comment]
@gokcehan Thanks for the review!

> There are some small issues with the documentation. First, `tag-toggle` in its current behavior is not a modal command so `(modal)` should be removed. Next, `tag` and `tag-toggle` should be added to the "Quick Reference" section as well. Lastly, `tags` file should be mentioned in the "Configuration" section.

Woops my bad, I will get this fixed.

> Have you considered tag toggling multiple files at once with the multiple selection? Ranger seems to work as such.

I did not notice this was possible so I will also try to port this feature :)

> Have you considered using `rune` instead of `byte` to be unicode friendly? More specifically, I think a tag is meant to be a single width character possibly consisting of multiple runes so the use of `string` might be required with some checks.

Thanks for pointing this out, I am not very familiar with go yet, so I did not know the difference between `byte` and `rune`. I understand that multiple runes can still result in a single width character, is there any way to check for this?

> Is there a reason `tag` is a modal command? This might prevent users from binding different keybindings for different tags. For example, if unicode tags are allowed (i.e. above point) some users may want to have different icons assigned to different keys.

There is actually no reason for this, I just implemented it this way to match the `mark-save` command but I think you're right. It would make more sense for it to not be modal.

> Should there be an option to configure the default tag? (maybe some of the above points might allow configuring the default tag without an explicit option)

I'll see if I can find a good way of doing this without extra options but I agree it should be possible to change the default.

> Regarding `tagcolor` option, some of our existing options uses fmt style configuration (e.g. `errorfmt`, `promptfmt`), so perhaps this should also be `tagfmt` for consistency.

Again, thanks for pointing this out. I implemented this "feature" kinda quickly and I am not completely familiar with the codebase yet. I will change this also.

> There has been some talk for adding configuration for selection/copy/move displays in [Improve status for colorblind users #754](https://github.com/gokcehan/lf/issues/754) which would then clash with tags. Is it possible to move the tag display to the next character right next to the filename as in ranger?

I think this should be possible, I'm close to getting something working like that :)

**Comment by sant0s12** [comment]
Thanks for the feedback!

> I think after tagging a file/folder the cursor shouldn't jump to next file/folder and it should remain on the tagged one.

I did this to match ranger's behavior but I guess it might be a good idea to have it as an option. 

> if I tag a file and then select that file there is not any sign that tell me that this file is tagged.for example I want to tag some files to remember copy them to another location but I want after selecting them `lf` somehow tell me that this files are tagged so I can be sure that I've selected the correct files.(I don't know if I explain that well or not)

I don't know if I understand exactly what you mean but maybe you're talking about the fact that the tag gets obscured by the selection color. If that is the case, this should be fixed if we move the tag right next to the icon (see above).

**Comment by gokcehan** [comment]
> > I think after tagging a file/folder the cursor shouldn't jump to next file/folder and it should remain on the tagged one.

> I did this to match ranger's behavior but I guess it might be a good idea to have it as an option.

@shabahengam @sant0s12 We had a similar discussion about this for `toggle` in #352 which was solved by removing shifting behavior from the command itself and changing the default keybinding to `map <space> :toggle; down` so users who prefer staying at the same position can simply use `map <space> toggle`. I think we can use a similar approach here for consistency.

> > Have you considered using `rune` instead of `byte` to be unicode friendly? More specifically, I think a tag is meant to be a single width character possibly consisting of multiple runes so the use of `string` might be required with some checks.

> Thanks for pointing this out, I am not very familiar with go yet, so I did not know the difference between `byte` and `rune`. I understand that multiple runes can still result in a single width character, is there any way to check for this?

We have been using [go-runewidth](https://github.com/mattn/go-runewidth) so far. There are functions `runeSliceWidth` and `runeSliceWidthRange` in `misc.go` and also `printLength` in `ui.go` which takes into account escape codes as well. Maybe they could be useful for this purpose.

@sant0s12 I should also say this patch is already working great and it would cover most use cases. I was just trying to have a brainstorm about what could be possible. So if you feel overwhelmed by the requests here, we can merge this patch as it is and leave the rest as possible future work. Please let me know when you are ready.

**Comment by shabahengam** [comment]
@sant0s12 
> but maybe you're talking about the fact that the tag gets obscured by the selection color.

yes, right know the tag sign `*` get obscured by the selection color.

@gokcehan 
>We had a similar discussion about this for toggle in #352 

I didn't know about that discussion, thanks for pointing that out.

**Comment by sant0s12** [comment]
@gokcehan @shabahengam I think this commit should address all of your input, please let me know if I'm missing anything :)

The way I handled having the tag right next to the icon was by having two cells overlapping each other. I hope that that is not too hacky.

**Comment by shabahengam** [comment]
if you select some files and then tag another file,things get weird.for example select some files and press `t`, all selected files get tagged and everything is OK but if you unselect on of them and press `t` on that file (or any other file) it acts weird.I mean you can not remove tag from that file unless you unselect all selected files.

**Comment by gokcehan** [comment]
I realized `tag-toggle` now takes an argument. Do we need a separate `tag` command then? What is the use case for `tag` command?

**Comment by sant0s12** [comment]
> I'm ok with the current behavior.

Nice :)

> There's a minor inconsistency with the style for directories and files which keeps the bold for directories and also changed the > length of the selection. I'll simply change it to reverse if that's ok.

Yes, I missed this. The problem with keeping reverse is that the background of the tag can be different than the background of the selection and I thought that looked strange. But that is a matter of opinion I guess :) Maybe there is a way to make it have the same background color as the selection (unless it's overwritten by `tagfmt`). That is what I was going for but it didn't quite work apparently.

> Also, moving down with multiple selection seems a little strange. Ranger seems to avoid this when multiple selections are involved. I'm thinking of changing the default keybinding to stay at the same position.

Yeah it probably makes sense to change the default.

> I realized tag-toggle now takes an argument. Do we need a separate tag command then? What is the use case for tag command?

The idea is that `tag-toggle` either sets the tag to the default (passed in the argument) or removes it if there is any tag. `tag` on the other hand just sets the tag to whatever is passed in the argument. This way the user can have a default tag but also have bindings for other tags. Maybe there is another way to do this but I think this way it works well.

**Comment by sant0s12** [comment]
@gokcehan

The changes make sense to me. I don't know if you're arguing for or against keeping the `tag` haha. Imo I would keep it because it allows retagging without double tapping and also what you said about clearing (pretty cool, I did not think about that).

But I guess it's up to you, I don't really care that much personally as I only really use the default tag.

**Comment by gokcehan** [comment]
@sant0s12 Currently I think I'm in favor of keeping the `tag` command :) Either that, or we could instead consider adding a builtin `tag-clear` command, which would similarly allow defining a tag command with `cmd tag :tag-clear; tag-toggle` but I think it is fine for now. Anyway, thanks again for the patch.

**Comment by jmckernon** [comment]
Hi all,

Thanks for the work on this. I'm a new lf user and this adds one of my most-missed ranger features. So far it seems to work as I would expect.

I do think that `tag-clear` should be a command in its own right, not just a definable composite of `tag` and `tag-toggle`. (Personally, I would call it `untag` for consistency with unselect, or it could be `tag_remove` as in ranger. But in any case I'm not here to bikeshed that.) And I think both `tag` and `tag-toggle` should stay; I can see a use for both of them.

I don't have much input to add beyond that, but thanks again.

**Comment by jmckernon** [comment]
I thought of one feature which would add to the usefulness of tags a lot. It would be good to be able to select all files in the current dir with a particular tag. Possibly also all tagged files (with any tag). Any chance this could be added? I'm not very experienced with go, but I could have a stab at writing a patch for this myself if there are no other takers.

**Comment by laktak** [comment]
I think `tagfmt` is missing from eval so you can't actually set the option.

**Comment by gokcehan** [comment]
@laktak You're right. I have pushed a fix now. Thanks for the heads up.

**Comment by yyy33** [comment]
> 我想到了一个可以大大增加标签有用性的功能。 能够选择当前目录中具有特定标签的所有文件会很好。 可能还有所有标记的文件（带有任何标记）。
> 
> 有没有可能添加这个？ 我对围棋不是很有经验，但如果没有其他人的话，我可以自己尝试为此编写一个补丁。



> I thought of one feature which would add to the usefulness of tags a lot. It would be good to be able to select all files in the current dir with a particular tag. Possibly also all tagged files (with any tag).
> 
> Any chance this could be added? I'm not very experienced with go, but I could have a stab at writing a patch for this myself if there are no other takers.

This would be cool, I think it would be possible to get a global tag manager that should have these features.
1. add tags to files or directories
2. Allow adding multiple tags to a file or directory
3. Add tags for directories with or without recursive tags for subdirectories and files
4. Quickly filter out files or directories that have tags based on their tags
5. Add some cute icons for different tags
通过DeepL翻译 https://www.deepl.com/app/?utm_medium=android-share

**Pull request merged**
