### PR TITLE
Add Winget Releaser workflow

### LINKED ISSUE #1047: create winget package ?

### PR DESCRIPTION
**Pull request by sitiom**
- Closes #1047

[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

**Before merging this:**
1. Add a **classic** PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.

example

2. Fork https://github.com/microsoft/winget-pkgs under @gokcehan. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.

You can test out the action inputs in this [playground](https://bittu.eu.org/docs/wr-playground).

If you want to see an example of a PR created using this action, see [microsoft/winget-pkgs/pulls (Pull request has been created with WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+created+with+WinGet+Releaser).

### CODE REVIEW

**Comment by gokcehan** [comment]
@sitiom Thanks for all the work. I'm still trying to figure out how this is supposed to work. More specifically, I wasn't sure in which repository I should add the winget token as a repo secret. I'm also not sure about dependabot as it might be a better to consciously update our dependencies as otherwise things can get broken easily (e.g. latest tcell does not seem to build properly for some reason). I might remove dependabot later on as I don't think it is necessary for the winget releaser.

**Comment by sitiom** [comment]
> More specifically, I wasn't sure in which repository I should add the winget token as a repo secret.

You should add it here where the workflow is.

> I'm also not sure about dependabot as it might be a better to consciously update our dependencies as otherwise things can get broken easily

Dependabot creates a PR to bump the dependency and does not directly commit to the repo. You can go ahead and review the changes yourself before you merge them. There were many cases where Winget Releaser did not successfully run due to an outdated version, so I thought this was necessary.

**Comment by gokcehan** [comment]
> Also, did you install [Pull](https://github.com/apps/pull) to https://github.com/gokcehan/winget-pkgs?

@sitiom In the [winget releaser readme](https://github.com/vedantmgoyal2009/winget-releaser), it says you can either give workflow permission to the token or use Pull. I tried the workflow permission approach as it sounded easier. Maybe it only updates the repo when the pipeline is run?

> Dependabot creates a PR to bump the dependency and does not directly commit to the repo. You can go ahead and review the changes yourself before you merge them. There were many cases where Winget Releaser did not successfully run due to an outdated version, so I thought this was necessary.

The issue with tcell version bump is now fixed and I have accepted all dependabot PRs. It seems like a useful addition, thanks again.

**Comment by sitiom** [comment]
> @sitiom In the [winget releaser readme](https://github.com/vedantmgoyal2009/winget-releaser), it says you can either give workflow permission to the token or use Pull. I tried the workflow permission approach as it sounded easier. Maybe it only updates the repo when the pipeline is run?

Oh well, yeah. I think that is fine as well.

**Comment by sitiom** [comment]
- https://github.com/microsoft/winget-pkgs/pull/103929

**Pull request merged**
