### PR TITLE
Update file permissions when returning from shell

### PR DESCRIPTION
**Pull request by bluesuncat**
Fixes https://github.com/gokcehan/lf/issues/1172

### CODE REVIEW

**Comment by bluesuncat** [comment]
Not sure why, but running app.ui.loadFile(app, true) here will not refresh the file information for the currently selected file, but selecting a different file and going back to the first one, will update the correct information.

This commit adds the same code that is executed when the user manually runs the reload command, but for some reason it does not behave the same way. Im a bit clueless as to why.

**Comment by bluesuncat** [comment]
Ok, I think I got this fixed.

This will now refresh the file information during the "draw" function before executing ui.drawPromptLine(nav) 

With this the file stats (like permissions) for the currently selected file are updated to reflect possible changed made on the shell (inside lf, e.g. by pressing w)

While this seems to work, I cannot say with confidence that I understand most of the things lf does in these functions, so there may be a better way to implement this. A closer review of this and possible side effects would be advised.

**Comment by gokcehan** [comment]
@bluesuncat I don't think it is a good idea to `reload` every time a shell command is used as it can be a heavy operation sometimes. Instead, you could selectively run reload in relevant custom commands if you don't like manual reloads for such occasions. For example, a reloading `chmod` can be defined as follows:

```
cmd chmod %{{
    chmod $1 $f
    lf -remote "send $id reload"
}}
```

**Comment by bluesuncat** [comment]
> @bluesuncat I don't think it is a good idea to `reload` every time a shell command is used as it can be a heavy operation sometimes. 

At the moment, the reload is only executed when returning from an interactive shell.
Using shell commands using : wont trigger the reload (but probably need the same fix)

However, I still think that there is another issue and a better fix here.

While this patch would reflect permission changes, changes like adding/deleting files seems to be ignored only for the current pane.

To demonstrate:

a

Now I press 'w' to get a shell and run 'rm -rf ../* to delete all files starting with the parent directory. Then I exit the shell to return to lf in this state:
b

As mentioned, I don't quite get how this works, but there obviously is a function that updated to parent and child pane of the current path to reflect file changes but the current path is unaffected. I assume this is a bug on its own and for the current path the "updatefilechanges" function is missing. But since it works without a reload, this is where the changes in file permission could probably also be fixed.

**Comment by bluesuncat** [comment]
There is a better and more complete solution to be found (hopefully)

**Pull request closed without merging**
