### PR TITLE
Add Temporary Marks

### PR DESCRIPTION
**Pull request by laktak**
see #743

I haven't written any go code in a while. Let me know if this looks good to you.

### CODE REVIEW

**Comment by laktak** [comment]
Note that `'` is added to the temporary marks by default. I'm not sure if this should be mentioned in the docs since `'` is special anyways.

**Comment by gokcehan** [comment]
@laktak Hey, thanks for the patch. I have tried it for a while and it seems to work great. A couple of questions below:

- There's some complication arising from the `tempmarks` option being local to each instance while the marks file being global. If we assume, `tempmarks` is only set in the lfrc file then there is no issue. But if we change the option from the command line manually (e.g. temporarily enabling `tempmarks` option within an instance), some corner cases pops up. For example, assume `set tempmarks a` in lfrc is overridden by `set tempmarks a:b` within an instance, then any `b` mark in the marks file will be deleted when a marks file update is triggered in the instance. I'm not sure if there is an easy fix for this case. It might as well be left alone as it is. I just wanted to bring it up to attention in case we can come up with a fix.
- Do you think the option can be a simple string option? (e.g. `set tempmarks "asdf"`). Aren't marks always a single character? If so, we may not need any delimiters and we can simply try iterating over the string rune by rune. In the future, we could also consider allowing ranges to be used as well (e.g. `set tempmarks "a-z"`) though I guess this might require disallowing some special characters (e.g. `-` in this case).
- I agree it would be nice to mention `'` mark somewhere in the documentation. Description of `tempmarks` option might be a good place. We could also add it to `Changing Directory` section, though I think special commands in this section runs in every dir change rather than only jumping dir changes so it could be slightly confusing.
- I think of `lfrc.example` as an example config file that users can use as a skeleton. So I try to keep it minimum. While `tempmarks` option can be quite useful when you look for it, I'm not sure if it is worth adding it here. What do you think?

**Comment by laktak** [comment]
- local/global: I can't think of a good way to handle this other than by documentation.
- string option: I don't have a preference, I just saw that you were using `:` in other options so I went with that. While I don't think ranges are necessary for this, if you want to add them later then I would stay with `:`.
- I misunderstood `lfrc.example` - I'll remove it there.
- I missed that `'` is already documented in `mark-load`: 
  > A special bookmark "'" holds the previous directory after a 'mark-load', 'cd', or 'select' command.

Let me know if this works for you:

> List of marks to treat as temporary. They are not synced to other clients and are not saved in the bookmarks file. This option should be specified only in the global config file ("lfrc") as it may otherwise cause unintended side effects. Please note 
that the special bookmark "'" is always treated as temporary and does not need to be specified.

**Comment by gokcehan** [comment]
@laktak Let's leave local/global as it is then. I might give it a try later on if I have some time.

For string option, I agree ranges are not that important so let's not consider them at this point. I still think `string` might be simpler over `[]string` along with its implementation in the code as `map[string]struct{}`. Note the latter also breaks our option value printing (e.g. `!echo $lf_tempmarks`).

Documentation seems fine. I might move some of the details to a new separate marks section later on. One minor thing is that we haven't called them "bookmarks" so far. I used the name "marks" to resemble the default keybinding for it (e.g. `m`).

**Comment by laktak** [comment]
OK, I'll change the option to be a simple string.

You are calling them bookmarks here:
https://github.com/gokcehan/lf/blob/930364ce7864d21fa70cd4214330886c953a42f1/doc.go#L412

Did you mean something else?

**Comment by gokcehan** [comment]
> You are calling them bookmarks here:

My bad sorry, my memory is failing, don't mind me.

Everything seems ok now. Thanks again for the patch.

**Pull request merged**
