### PR TITLE
UI improvement

### PR DESCRIPTION
**Pull request by sutrisnob45**
### Before
before

### After
after

### CODE REVIEW

**Comment by sutrisnob45** [comment]
icons is directly taken from ranger devicons, don't know if it work on windows

**Comment by Monirzadeh** [comment]
same problem here because of `$LF_ICONS` variable

**Comment by Limero** [comment]
I think the new icons look better, but I'm unsure about replacing colored selection bars with a tiny indentation and different text color. I assume this makes it more difficult for color blind people to differentiate what is a selection and what isn't.

**Comment by sutrisnob45** [comment]
> can you check [this problem](https://github.com/gokcehan/lf/issues/265) solve with your commit?

since [this commit](https://github.com/gokcehan/lf/pull/257/commits/93a8fe6dcbb640054818f8abb21b4c82aa3ab021) remove permission checking and apply icons based on type (folder or file) and name, i think it can

**Comment by gokcehan** [comment]
@sutrisnob45 So this patch seems to make things closer to ranger. Is there a reason ranger uses this style for marking? We have some different semantics in lf that would not work in this scheme. For example we share the copy/cut files in the server and those should be marked differently than selected files. Also we have a global selection scheme that works across multiple directories whereas ranger selection only works within a single directory. We also talked about adding number of selected files to the bottom ruler so users are aware of selected files in directories not shown. For this purpose, it's better to have color codes for file selection.

It would be nice to have some more builtin icons, but those icons are from a custom patched font and not unicode standard. I don't think it's a good idea to have such icons builtin.

**Comment by sutrisnob45** [comment]
I dunno why ranger use this style, but maybe we should make accessibility support an option 🤔

I agree about the icons

**Comment by gokcehan** [comment]
@sutrisnob45 I don't know if either of these is better in terms of accessibility. Color blind people may be able to change the terminal colors for easier differentiation. I think it's best to discuss these before making any changes. So what shall we do about this patch?

**Comment by Monirzadeh** [comment]
> @sutrisnob45 I don't know if either of these is better in terms of accessibility. Color blind people may be able to change the terminal colors for easier differentiation. I think it's best to discuss these before making any changes. So what shall we do about this patch?

better icon support in this patch :+1: :heart: 
i prefer default selection (line beside the file) it can be optional :-1: 
i am not sure that is a good idea to number get their color from file type color (it is so clutter)

**Comment by gokcehan** [comment]
@sutrisnob45 Closing this PR. Feel free to discuss changes in an issue first before sending a PR.

**Pull request closed without merging**
